### PR TITLE
Adding support for AIM v2 to LLaVA

### PR DESCRIPTION
**Pull request by hi-wesley**
High-level summary: 
Currently, LLaVA takes a CLIP-based tower as its vision encoder. 
I add support for AIM v2 and attempt to run a sample inference (Feed LLaVA a simple prompt "Describe this image" plus the ramen as a test image. 

Add support for AIM v2, a family of large-scale vision encoders developed by Apple, using a multimodal autoregressive approach. 
- Created new file aimv2_encoder.py in llava/model/multimodal_encoder/aimv2_encoder.py, a custom vision tower 
- Patched builder.py in llava/model/multimodal_encoder/builder.py to register the new vision tower 

AIM v2 is not available in older versions of transformers 
- Updated pyproject.toml dependencies to support AIM v2 

ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' 
- Got rid of unnecessary (circular) import in llava/\_\_init\_\_.py 

The current version of transformers sends a new argument called cache_position to the model's forward() call 
- Updated llava\model\language_model\llava_llama.py to accept cache_position

### CODE REVIEW

File: llava/model/language_model/llava_llama.py
[the remark this answers is not in the document]
Comment (hi-wesley) [reply llava/model/language_model/llava_llama.py:1]: It will throw: TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position' 

If llava_llama.py isn't changed because of the update to transformers (4.37.2 to 4.54.*), transformers now sends a new argument called cache_position into the model's forward() call. 

Here's a note from a project that also had to add cache_position due to updating transformers: https://github.com/1zhou-Wang/MemVR 
"Please note that due to the change of transformers lib, you need to modify the forward() function defined at llava_llama.py, line 70. Add cache_position=None to it."

File: scripts/v1_5/pretrain_llava_aimv2.sh [hunk 1]
```diff
@@ -18,7 +18,6 @@ deepspeed llava/train/train.py \
     --per_device_train_batch_size 8 \
     --per_device_eval_batch_size 4 \
     --gradient_accumulation_steps 4 \
-    --evaluation_strategy no \
```
[the remark this answers is not in the document]
Comment (hi-wesley) [reply scripts/v1_5/pretrain_llava_aimv2.sh]: It will throw: ValueError: Some specified arguments are not used by the HfArgumentParser: ['--evaluation_strategy', 'no'] 

The LLaVA scripts working with transformers 4.37.2 have different argument handling than the current version 4.54.*, which is stricter. 

The current version of transformers defaults to no evaluation during training without passing in the argument.

File: scripts/v1_5/pretrain_llava_aimv2.sh [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+    --weight_decay 0. \
+    --warmup_ratio 0.03 \
+    --lr_scheduler_type cosine \
+    --logging_steps 1 \
+    --tf32 True \
+    --model_max_length 2048 \
+    --gradient_checkpointing True \
+    --dataloader_num_workers 4 \
+    --lazy_preprocess True \
+    --report_to none
```
Comment (nahidalam) [inline scripts/v1_5/pretrain_llava_aimv2.sh:35]: in the final PR, please add wandb after testing

Comment (hi-wesley) [reply scripts/v1_5/pretrain_llava_aimv2.sh]: Added wandb after testing
